/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FindItem.java
 *
 * Created on 08-06-2010, 13:26:39
 */

package GUI;

import Ctr.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Erik
 */
public class FindItem extends javax.swing.JFrame {

        private ItemCtr itemCtr;

    /** Creates new form FindItem */
    public FindItem() {
        initComponents();
        itemCtr = new ItemCtr();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtItemDetails = new java.awt.TextArea();
        txtItemID = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Find vare"));

        txtItemDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtItemDetails.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                txtItemDetailsMouseWheelMoved(evt);
            }
        });
        txtItemDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtItemDetailsMouseClicked(evt);
            }
        });
        txtItemDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtItemDetailsComponentShown(evt);
            }
        });
        txtItemDetails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemDetailsFocusGained(evt);
            }
        });
        txtItemDetails.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemDetailsKeyPressed(evt);
            }
        });

        jButton2.setText("Søg");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label1.setText("Vare-ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtItemID, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                    .addComponent(txtItemDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtItemDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtItemDetailsMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_txtItemDetailsMouseWheelMoved
        // TODO add your handling code here:
}//GEN-LAST:event_txtItemDetailsMouseWheelMoved

    private void txtItemDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtItemDetailsMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_txtItemDetailsMouseClicked

    private void txtItemDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtItemDetailsComponentShown
        // TODO add your handling code here:
}//GEN-LAST:event_txtItemDetailsComponentShown

    private void txtItemDetailsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemDetailsFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_txtItemDetailsFocusGained

    private void txtItemDetailsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemDetailsKeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_txtItemDetailsKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        StringBuffer b = new StringBuffer();
        int itemID = Integer.parseInt(txtItemID.getText());
        if(itemCtr.getItem(itemID) != null) {
            b.append("Varenavn: " + itemCtr.getItem(itemID).getItemName() + "\n");
            b.append("Pris: " + itemCtr.getItem(itemID).getItemPrice() + "\n");
            b.append("Beskrivelse: " + itemCtr.getItem(itemID).getDescription() + "\n");
            b.append("Maksimumsbeholdning: " + itemCtr.getItem(itemID).getMaxInStock() + "\n");
            b.append("Minimumsbeholdning: " + itemCtr.getItem(itemID).getMinInStock() + "\n");
            b.append("Antal: " + itemCtr.getItem(itemID).getItemsInStock() + "\n");
            b.append("Brand: " + itemCtr.getItem(itemID).getBrand() + "\n");
            txtItemDetails.setText(b.toString());
        } else {
            JOptionPane.showMessageDialog(this, "ID'et blev ikke fundet");
        }
}//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.TextArea txtItemDetails;
    private javax.swing.JTextField txtItemID;
    // End of variables declaration//GEN-END:variables

}
