/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUISale.java
 *
 * Created on 10-06-2010, 10:14:58
 */
package GUI;

import Ctr.EmployeeCtr;
import javax.swing.JOptionPane;
import Ctr.SaleCtr;
import Ctr.ItemCtr;
import Model.Employee;
import Model.Item;
import java.util.ArrayList;
import Model.Sale;
import javax.swing.JTextField;

/**
 *
 * @author Glerup
 */
public class GUISale extends javax.swing.JPanel {

    private SaleCtr saleCtr;
    private TableSale tblSale;
    private ItemCtr itemCtr;
    private EmployeeCtr employeeCtr;

    /** Creates new form GUISale */
    public GUISale() {
        initComponents();
        saleCtr = new SaleCtr();
        tblSale = new TableSale();
        itemCtr = new ItemCtr();
        employeeCtr = new EmployeeCtr();
    }

    public void updateSaleList() {
        ArrayList<Sale> saleList = saleCtr.getSaleList();
        tblSale.setData(saleList);
        tblSaleList.setModel(tblSale);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pSale = new javax.swing.JPanel();
        pSaleList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSaleList = new javax.swing.JTable();
        pFindSale = new javax.swing.JPanel();
        btnSaleSearch = new javax.swing.JButton();
        txtSeachSaleID = new javax.swing.JTextField();
        pCreateSale = new javax.swing.JPanel();
        lblSaleDate = new javax.swing.JLabel();
        lblSaleItemQuantity = new javax.swing.JLabel();
        lblSaleEmployeeID = new javax.swing.JLabel();
        lblSaleItemID = new javax.swing.JLabel();
        txtSaleItemID = new javax.swing.JTextField();
        txtSaleEmployeeID = new javax.swing.JTextField();
        txtSaleItemQuantity = new javax.swing.JTextField();
        txtSaleDate = new javax.swing.JTextField();
        btnCreateSale = new javax.swing.JButton();

        pSale.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salg", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        pSale.setPreferredSize(new java.awt.Dimension(500, 399));

        pSaleList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        tblSaleList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Salg-ID", "Dato", "Samlet pris", "Medarbejder-ID"
            }
        ));
        jScrollPane1.setViewportView(tblSaleList);

        javax.swing.GroupLayout pSaleListLayout = new javax.swing.GroupLayout(pSaleList);
        pSaleList.setLayout(pSaleListLayout);
        pSaleListLayout.setHorizontalGroup(
            pSaleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSaleListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );
        pSaleListLayout.setVerticalGroup(
            pSaleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSaleListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pFindSale.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Søg efter salg", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        btnSaleSearch.setText("Søg");
        btnSaleSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleSearchActionPerformed(evt);
            }
        });

        txtSeachSaleID.setText("Indtast ID");
        txtSeachSaleID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSeachSaleIDFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pFindSaleLayout = new javax.swing.GroupLayout(pFindSale);
        pFindSale.setLayout(pFindSaleLayout);
        pFindSaleLayout.setHorizontalGroup(
            pFindSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFindSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(txtSeachSaleID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        pFindSaleLayout.setVerticalGroup(
            pFindSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFindSaleLayout.createSequentialGroup()
                .addGroup(pFindSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaleSearch)
                    .addComponent(txtSeachSaleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCreateSale.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opret salg", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        lblSaleDate.setText("Dato");

        lblSaleItemQuantity.setText("Antal");

        lblSaleEmployeeID.setText("Medarbejder");

        lblSaleItemID.setText("Vare");

        txtSaleItemID.setText("Indtast ID");
        txtSaleItemID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSaleItemIDFocusGained(evt);
            }
        });

        txtSaleEmployeeID.setText("Indtast ID");
        txtSaleEmployeeID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSaleEmployeeIDFocusGained(evt);
            }
        });
        txtSaleEmployeeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaleEmployeeIDKeyTyped(evt);
            }
        });

        txtSaleItemQuantity.setText("Hele tal");
        txtSaleItemQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaleItemQuantityActionPerformed(evt);
            }
        });
        txtSaleItemQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSaleItemQuantityFocusGained(evt);
            }
        });

        txtSaleDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSaleDateFocusGained(evt);
            }
        });

        btnCreateSale.setText("Opret");
        btnCreateSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCreateSaleLayout = new javax.swing.GroupLayout(pCreateSale);
        pCreateSale.setLayout(pCreateSaleLayout);
        pCreateSaleLayout.setHorizontalGroup(
            pCreateSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCreateSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCreateSaleLayout.createSequentialGroup()
                        .addGroup(pCreateSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSaleItemQuantity)
                            .addComponent(lblSaleDate)
                            .addComponent(lblSaleItemID)
                            .addComponent(lblSaleEmployeeID))
                        .addGap(21, 21, 21)
                        .addGroup(pCreateSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSaleDate)
                            .addComponent(txtSaleItemQuantity)
                            .addComponent(txtSaleItemID)
                            .addComponent(txtSaleEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pCreateSaleLayout.createSequentialGroup()
                        .addComponent(btnCreateSale, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(116, 116, 116)))
                .addContainerGap())
        );
        pCreateSaleLayout.setVerticalGroup(
            pCreateSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCreateSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaleEmployeeID)
                    .addComponent(txtSaleEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaleItemID)
                    .addComponent(txtSaleItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pCreateSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaleItemQuantity)
                    .addComponent(txtSaleItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCreateSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaleDate)
                    .addComponent(txtSaleDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnCreateSale)
                .addContainerGap())
        );

        javax.swing.GroupLayout pSaleLayout = new javax.swing.GroupLayout(pSale);
        pSale.setLayout(pSaleLayout);
        pSaleLayout.setHorizontalGroup(
            pSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pSaleList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pFindSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pCreateSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        pSaleLayout.setVerticalGroup(
            pSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSaleLayout.createSequentialGroup()
                .addGroup(pSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSaleLayout.createSequentialGroup()
                        .addComponent(pFindSale, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pSaleList, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pCreateSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSale, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSale, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaleSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleSearchActionPerformed
        // TODO add your handling code here:
        try {
            int saleID = Integer.parseInt(txtSeachSaleID.getText());
            if (saleCtr.getSale(saleID) != null) {
            } else {
                JOptionPane.showMessageDialog(this, "ID'et " + saleID + " blev ikke fundet");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fejl: " + e.getMessage());
        }
}//GEN-LAST:event_btnSaleSearchActionPerformed

    private void btnCreateSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSaleActionPerformed
        // TODO add your handling code here:
        try {
            int itemID = Integer.parseInt(txtSaleItemID.getText());
            int employeeID = Integer.parseInt(txtSaleEmployeeID.getText());
            int quantity = Integer.parseInt(txtSaleItemQuantity.getText());
            Item i = itemCtr.getItem(itemID);
            Employee e = employeeCtr.getEmployee(employeeID);
            if (i == null && e == null) {
                JOptionPane.showMessageDialog(this, "Fejl: Både vare-ID'et " + itemID
                        + " og medarbejder-ID'et " + employeeID + " findes ikke");
            } else {
                if (e == null) {
                    JOptionPane.showMessageDialog(this, "Fejl: Medarbejder-ID'et " + employeeID + " findes ikke");
                } else {
                    if (i == null) {
                        JOptionPane.showMessageDialog(this, "Fejl: Vare-ID'et " + itemID + "findes ikke");
                    } else {
                        if (quantity > i.getItemsInStock()) {
                            JOptionPane.showMessageDialog(this, "Fejl: Antallet overskrider lagerbeholdningen, som er på " + i.getItemsInStock());
                        } else {
                            String date = txtSaleItemQuantity.getText();
                            int saleID = saleCtr.createSale(employeeID, itemID, date, quantity);
                            updateSaleList();
                            NewSale newSale = new NewSale();
                            newSale.setVisible(true);
                            newSale.setSaleID(saleID);
                            newSale.setGuiSale(this);
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fejl: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCreateSaleActionPerformed

    private void txtSaleItemIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSaleItemIDFocusGained
        // TODO add your handling code here:
        txtSaleItemID.setText("");
    }//GEN-LAST:event_txtSaleItemIDFocusGained

    private void txtSaleEmployeeIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSaleEmployeeIDFocusGained
        // TODO add your handling code here:
        txtSaleEmployeeID.setText("");
    }//GEN-LAST:event_txtSaleEmployeeIDFocusGained

    private void txtSaleItemQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSaleItemQuantityFocusGained
        // TODO add your handling code here:
        txtSaleItemQuantity.setText("");
    }//GEN-LAST:event_txtSaleItemQuantityFocusGained

    private void txtSaleDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSaleDateFocusGained
        // TODO add your handling code here:
        txtSaleDate.setText("");
    }//GEN-LAST:event_txtSaleDateFocusGained

    private void txtSeachSaleIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSeachSaleIDFocusGained
        // TODO add your handling code here:
        txtSeachSaleID.setText("");
    }//GEN-LAST:event_txtSeachSaleIDFocusGained

    private void txtSaleEmployeeIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaleEmployeeIDKeyTyped
        // TODO add your handling code here:
        txtSaleDate.setText("Test");
    }//GEN-LAST:event_txtSaleEmployeeIDKeyTyped

    private void txtSaleItemQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaleItemQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaleItemQuantityActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateSale;
    private javax.swing.JButton btnSaleSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSaleDate;
    private javax.swing.JLabel lblSaleEmployeeID;
    private javax.swing.JLabel lblSaleItemID;
    private javax.swing.JLabel lblSaleItemQuantity;
    private javax.swing.JPanel pCreateSale;
    private javax.swing.JPanel pFindSale;
    private javax.swing.JPanel pSale;
    private javax.swing.JPanel pSaleList;
    private javax.swing.JTable tblSaleList;
    private javax.swing.JTextField txtSaleDate;
    private javax.swing.JTextField txtSaleEmployeeID;
    private javax.swing.JTextField txtSaleItemID;
    private javax.swing.JTextField txtSaleItemQuantity;
    private javax.swing.JTextField txtSeachSaleID;
    // End of variables declaration//GEN-END:variables
}
