/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListAllItems.java
 *
 * Created on 08-06-2010, 10:00:13
 */
package GUI;

import Model.Item;
import Ctr.*;

/**
 *
 * @author Erik
 */
public class ListAllItems extends javax.swing.JFrame {
    private ItemCtr itemCtr;

    /** Creates new form ListAllItems */
    public ListAllItems() {
        initComponents();
        itemCtr = new ItemCtr();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtListAllItems = new java.awt.TextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ItemList"));

        txtListAllItems.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtListAllItems.setEditable(false);
        txtListAllItems.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                txtListAllItemsMouseWheelMoved(evt);
            }
        });
        txtListAllItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtListAllItemsMouseClicked(evt);
            }
        });
        txtListAllItems.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtListAllItemsComponentShown(evt);
            }
        });
        txtListAllItems.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtListAllItemsFocusGained(evt);
            }
        });
        txtListAllItems.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtListAllItemsKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtListAllItems, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtListAllItems, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtListAllItemsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtListAllItemsComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_txtListAllItemsComponentShown

    private void txtListAllItemsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtListAllItemsFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtListAllItemsFocusGained

    private void txtListAllItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtListAllItemsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtListAllItemsMouseClicked

    private void txtListAllItemsMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_txtListAllItemsMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtListAllItemsMouseWheelMoved

    private void txtListAllItemsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtListAllItemsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtListAllItemsKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                        StringBuffer b = new StringBuffer();
        for(Item i : itemCtr.getItemList())
	{
            b.append("Vare-ID: " + i.getItemID() + " Varenavn: " +
                    i.getItemName() + " Pris: " + i.getItemPrice() +
                    " Antal: " + i.getItemsInStock() + " Brand: " +
                    i.getBrand() + " Lokation: " + i.getPlace());
	}
        b.append("gsdgsdg\n");
        b.append("fefwf\n");
        txtListAllItems.append(b.toString());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ListAllItems().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextArea txtListAllItems;
    // End of variables declaration//GEN-END:variables
}
