/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewSale2.java
 *
 * Created on 10-06-2010, 12:09:09
 */
package GUI;

import Model.Customer;
import Ctr.SaleCtr;
import javax.swing.JOptionPane;
import Ctr.CustomerCtr;
import Ctr.ItemCtr;
import Model.Item;
import Model.SalesLineItem;
import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author Glerup
 */
public class NewSale extends javax.swing.JFrame {

    private SaleCtr saleCtr;
    private CustomerCtr customerCtr;
    private int saleID;
    private TableNewSale tblNewSale;
    private GUISale guiSale;
    private ItemCtr itemCtr;

    /** Creates new form NewSale */
    public NewSale() {
        initComponents();
        saleCtr = new SaleCtr();
        customerCtr = new CustomerCtr();
        saleID = 0;
        tblNewSale = new TableNewSale();
        itemCtr = new ItemCtr();
    }

    public void setGuiSale(GUISale guiSale) {
        this.guiSale = guiSale;
    }

    public void updateSliList() {
        ArrayList<SalesLineItem> sliList = saleCtr.getSLIList(saleID);
        tblNewSale.setData(sliList);
        tblNewSaleList.setModel(tblNewSale);
        this.setVisible(true);
    }

    public void setSaleID(int saleID) {
        this.saleID = saleID;

    }

    public void resetFields(JTextField[] textFields) {
        for (JTextField txtField : textFields) {
            txtField.setText("");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNewSale = new javax.swing.JPanel();
        pContentsOfSale = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNewSaleList = new javax.swing.JTable();
        pCustomer = new javax.swing.JPanel();
        lblCustomerID = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblCustomerAddress = new javax.swing.JLabel();
        lblCustomerPhone = new javax.swing.JLabel();
        txtCustomerPhone = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerAddress = new javax.swing.JTextField();
        txtCustomerID = new javax.swing.JTextField();
        pAddOrRemoveCustomer = new javax.swing.JPanel();
        txtAddOrRemoveCustomerID = new javax.swing.JTextField();
        btnAddCustomer = new javax.swing.JButton();
        btnRemoveCustomer = new javax.swing.JButton();
        pAddItem = new javax.swing.JPanel();
        txtItemID = new javax.swing.JTextField();
        btnAddSLI = new javax.swing.JButton();
        lblItemID = new javax.swing.JLabel();
        lblItemQuantity = new javax.swing.JLabel();
        txtItemQuantity = new javax.swing.JTextField();
        pAddDiscount = new javax.swing.JPanel();
        txtAddQuantityDiscount = new javax.swing.JTextField();
        btnAddQuantityDiscount = new javax.swing.JButton();
        btnResetQuantityDiscount = new javax.swing.JButton();
        txtPickupDiscount = new javax.swing.JTextField();
        btnAddPickDiscount = new javax.swing.JButton();
        btnResetPickupDiscount = new javax.swing.JButton();
        lblQuantityDiscount = new javax.swing.JLabel();
        lblPickupDiscount = new javax.swing.JLabel();
        lblTotalDiscount = new javax.swing.JLabel();
        btnEndSale = new javax.swing.JButton();
        btnCancelSale = new javax.swing.JButton();
        pRemoveItem = new javax.swing.JPanel();
        txtRemoveSLIID = new javax.swing.JTextField();
        btnRemoveSLI = new javax.swing.JButton();
        lblSLI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pNewSale.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nyt Salg", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        pNewSale.setPreferredSize(new java.awt.Dimension(1024, 768));

        pContentsOfSale.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salgets indhold", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        pContentsOfSale.setPreferredSize(new java.awt.Dimension(749, 241));

        tblNewSaleList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Salgsvare-ID", "Vare-ID", "Antal", "Samlet pris"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNewSaleList);

        pCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Kundeoplysninger"));

        lblCustomerID.setText("Kunde-ID");

        lblCustomerName.setText("Navn");

        lblCustomerAddress.setText("Adresse");

        lblCustomerPhone.setText("Tlfnr.");

        txtCustomerPhone.setEditable(false);

        txtCustomerName.setEditable(false);

        txtCustomerAddress.setEditable(false);

        txtCustomerID.setEditable(false);

        javax.swing.GroupLayout pCustomerLayout = new javax.swing.GroupLayout(pCustomer);
        pCustomer.setLayout(pCustomerLayout);
        pCustomerLayout.setHorizontalGroup(
            pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCustomerLayout.createSequentialGroup()
                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCustomerAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerPhone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCustomerPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap())
        );
        pCustomerLayout.setVerticalGroup(
            pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomerLayout.createSequentialGroup()
                .addComponent(lblCustomerID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCustomerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCustomerAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCustomerPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pContentsOfSaleLayout = new javax.swing.GroupLayout(pContentsOfSale);
        pContentsOfSale.setLayout(pContentsOfSaleLayout);
        pContentsOfSaleLayout.setHorizontalGroup(
            pContentsOfSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContentsOfSaleLayout.createSequentialGroup()
                .addComponent(pCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pContentsOfSaleLayout.setVerticalGroup(
            pContentsOfSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContentsOfSaleLayout.createSequentialGroup()
                .addGroup(pContentsOfSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pAddOrRemoveCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tilføj/fjern kunde", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        txtAddOrRemoveCustomerID.setText("Indtast ID");
        txtAddOrRemoveCustomerID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddOrRemoveCustomerIDFocusGained(evt);
            }
        });

        btnAddCustomer.setText("Tilføj");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnRemoveCustomer.setText("Fjern");
        btnRemoveCustomer.setEnabled(false);
        btnRemoveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAddOrRemoveCustomerLayout = new javax.swing.GroupLayout(pAddOrRemoveCustomer);
        pAddOrRemoveCustomer.setLayout(pAddOrRemoveCustomerLayout);
        pAddOrRemoveCustomerLayout.setHorizontalGroup(
            pAddOrRemoveCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddOrRemoveCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAddOrRemoveCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoveCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );
        pAddOrRemoveCustomerLayout.setVerticalGroup(
            pAddOrRemoveCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddOrRemoveCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAddOrRemoveCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAddOrRemoveCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddCustomer)
                        .addComponent(btnRemoveCustomer))
                    .addComponent(txtAddOrRemoveCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pAddItem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tilføj salgsvare", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        txtItemID.setText("Indtast ID");
        txtItemID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemIDFocusGained(evt);
            }
        });

        btnAddSLI.setText("Tilføj");
        btnAddSLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSLIActionPerformed(evt);
            }
        });

        lblItemID.setText("Vare-ID");

        lblItemQuantity.setText("Antal");

        txtItemQuantity.setText("Hele tal");
        txtItemQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemQuantityFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pAddItemLayout = new javax.swing.GroupLayout(pAddItem);
        pAddItem.setLayout(pAddItemLayout);
        pAddItemLayout.setHorizontalGroup(
            pAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItemID)
                    .addComponent(lblItemQuantity)
                    .addComponent(btnAddSLI, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemID, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(txtItemQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap())
        );
        pAddItemLayout.setVerticalGroup(
            pAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblItemID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItemQuantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddSLI))
        );

        pAddDiscount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rabat (i procent)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        txtAddQuantityDiscount.setText("Indtast % i hel tal");
        txtAddQuantityDiscount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddQuantityDiscountFocusGained(evt);
            }
        });

        btnAddQuantityDiscount.setText("Tilføj");
        btnAddQuantityDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQuantityDiscountActionPerformed(evt);
            }
        });

        btnResetQuantityDiscount.setText("Nulstil");
        btnResetQuantityDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetQuantityDiscountActionPerformed(evt);
            }
        });

        txtPickupDiscount.setText("Indtast % i hel tal");
        txtPickupDiscount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPickupDiscountFocusGained(evt);
            }
        });

        btnAddPickDiscount.setText("Tilføj");
        btnAddPickDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPickDiscountActionPerformed(evt);
            }
        });

        btnResetPickupDiscount.setText("Nulstil");
        btnResetPickupDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPickupDiscountActionPerformed(evt);
            }
        });

        lblQuantityDiscount.setText("Mængderabat");

        lblPickupDiscount.setText("Afhentningsrabat");

        lblTotalDiscount.setText("Total rabat:");

        javax.swing.GroupLayout pAddDiscountLayout = new javax.swing.GroupLayout(pAddDiscount);
        pAddDiscount.setLayout(pAddDiscountLayout);
        pAddDiscountLayout.setHorizontalGroup(
            pAddDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddDiscountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAddDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantityDiscount)
                    .addGroup(pAddDiscountLayout.createSequentialGroup()
                        .addComponent(txtAddQuantityDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddQuantityDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnResetQuantityDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblPickupDiscount)
                    .addGroup(pAddDiscountLayout.createSequentialGroup()
                        .addComponent(txtPickupDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddPickDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResetPickupDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                    .addComponent(lblTotalDiscount))
                .addContainerGap())
        );
        pAddDiscountLayout.setVerticalGroup(
            pAddDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddDiscountLayout.createSequentialGroup()
                .addComponent(lblQuantityDiscount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAddDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAddDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnResetQuantityDiscount)
                        .addComponent(btnAddQuantityDiscount))
                    .addComponent(txtAddQuantityDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblPickupDiscount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAddDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAddDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddPickDiscount)
                        .addComponent(btnResetPickupDiscount))
                    .addComponent(txtPickupDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTotalDiscount))
        );

        btnEndSale.setText("Afslut salg");
        btnEndSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndSaleActionPerformed(evt);
            }
        });

        btnCancelSale.setText("Annuller salg");
        btnCancelSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSaleActionPerformed(evt);
            }
        });

        pRemoveItem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fjern salgsvare", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        txtRemoveSLIID.setText("Indtast ID");
        txtRemoveSLIID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRemoveSLIIDFocusGained(evt);
            }
        });

        btnRemoveSLI.setText("Fjern");
        btnRemoveSLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSLIActionPerformed(evt);
            }
        });

        lblSLI.setText("Salgsvare");

        javax.swing.GroupLayout pRemoveItemLayout = new javax.swing.GroupLayout(pRemoveItem);
        pRemoveItem.setLayout(pRemoveItemLayout);
        pRemoveItemLayout.setHorizontalGroup(
            pRemoveItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRemoveItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRemoveItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSLI)
                    .addComponent(txtRemoveSLIID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveSLI, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pRemoveItemLayout.setVerticalGroup(
            pRemoveItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRemoveItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSLI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRemoveSLIID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnRemoveSLI))
        );

        javax.swing.GroupLayout pNewSaleLayout = new javax.swing.GroupLayout(pNewSale);
        pNewSale.setLayout(pNewSaleLayout);
        pNewSaleLayout.setHorizontalGroup(
            pNewSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNewSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pContentsOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNewSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pNewSaleLayout.createSequentialGroup()
                        .addGroup(pNewSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEndSale, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pNewSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelSale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pAddDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pAddOrRemoveCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pNewSaleLayout.setVerticalGroup(
            pNewSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNewSaleLayout.createSequentialGroup()
                .addGroup(pNewSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pContentsOfSale, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pNewSaleLayout.createSequentialGroup()
                        .addComponent(pAddOrRemoveCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pNewSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pAddDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pNewSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelSale)
                            .addComponent(btnEndSale))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pNewSale, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pNewSale, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        try {
            int customerID = Integer.parseInt(txtAddOrRemoveCustomerID.getText());
            Customer c = customerCtr.getCustomer(customerID);
            if (c != null) {
                saleCtr.addCustomerToSale(saleID, customerID);

                btnAddCustomer.setEnabled(false);
                btnRemoveCustomer.setEnabled(true);
                txtCustomerID.setText(Integer.toString(customerID));
                txtCustomerName.setText(c.getName());
                txtCustomerAddress.setText(c.getAddress());
                txtCustomerPhone.setText(c.getPhone());
            } else {
                JOptionPane.showMessageDialog(this, "ID'et " + customerID + " blev ikke fundet");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kunde ID findes ikke");
        }
}//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnRemoveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCustomerActionPerformed
        // TODO add your handling code here:
        try {
            saleCtr.removeCustomerFromSale(saleID);
            btnAddCustomer.setEnabled(true);
            btnRemoveCustomer.setEnabled(false);
            JTextField[] txtFields = {txtCustomerID, txtCustomerName,
                txtCustomerAddress, txtCustomerPhone};
            resetFields(txtFields);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kunde ID findes ikke");
        }
}//GEN-LAST:event_btnRemoveCustomerActionPerformed

    private void btnAddSLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSLIActionPerformed
        // TODO add your handling code here:
        try {
            int itemQuantity = Integer.parseInt(txtItemQuantity.getText());
            int itemID = Integer.parseInt(txtItemID.getText());
            int itemsInStock = itemCtr.getItem(itemID).getItemsInStock();
            Item i = itemCtr.getItem(itemID);
            if (i == null) {
                JOptionPane.showMessageDialog(this, "ID'et " + itemID + " findes ikke");
            } else {
                if (itemsInStock < itemQuantity) {
                    JOptionPane.showMessageDialog(this, "Den indtastede " + itemQuantity + " overskrider lagerbeholdningen, som er på " + itemsInStock);
                } else {
                    saleCtr.addSalesLineItem(saleID, itemID, itemQuantity);
                    txtItemID.setText("");
                    txtItemQuantity.setText("");
                    updateSliList();
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Følgende felter skal indeholde et heltal: Antal/vare-ID");
        }
}//GEN-LAST:event_btnAddSLIActionPerformed

    private void btnAddQuantityDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQuantityDiscountActionPerformed
        // TODO add your handling code here:
        double newDiscount = Double.parseDouble(txtAddQuantityDiscount.getText());
        double discount = 1 - (newDiscount / 100);
        saleCtr.getSale(saleID).getDiscount().setQuantityDiscount(discount);
        txtAddQuantityDiscount.setText("");
}//GEN-LAST:event_btnAddQuantityDiscountActionPerformed

    private void btnResetQuantityDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetQuantityDiscountActionPerformed
        // TODO add your handling code here:
        saleCtr.getSale(saleID).getDiscount().setPickupDiscount(1);
        txtAddQuantityDiscount.setText("");
}//GEN-LAST:event_btnResetQuantityDiscountActionPerformed

    private void btnAddPickDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPickDiscountActionPerformed
        // TODO add your handling code here:
        double newDiscount = Double.parseDouble(txtPickupDiscount.getText());
        double discount = 1 - (newDiscount / 100);
        saleCtr.setPickupDiscount(discount);
        txtPickupDiscount.setText("");
}//GEN-LAST:event_btnAddPickDiscountActionPerformed

    private void btnResetPickupDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPickupDiscountActionPerformed
        // TODO add your handling code here:
        saleCtr.getSale(saleID).getDiscount().setPickupDiscount(1);
        txtPickupDiscount.setText("");
}//GEN-LAST:event_btnResetPickupDiscountActionPerformed

    private void btnEndSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndSaleActionPerformed
        // TODO add your handling code here:
        saleCtr.endSale(saleID);
        guiSale.updateSaleList();
        //dispose();
        setVisible(false);
}//GEN-LAST:event_btnEndSaleActionPerformed

    private void btnCancelSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSaleActionPerformed
        // TODO add your handling code here:
        saleCtr.cancelSale(saleID);
        guiSale.updateSaleList();
        setVisible(false);
}//GEN-LAST:event_btnCancelSaleActionPerformed

    private void btnRemoveSLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSLIActionPerformed
        // TODO add your handling code here:
        try {
            int sLIID = Integer.parseInt(txtRemoveSLIID.getText());
            if(saleCtr.getSale(saleID) != null) {
                            saleCtr.removeSalesLineItem(saleID, sLIID);
            updateSliList();
            }
            else {
                JOptionPane.showMessageDialog(this, "ID'et " + sLIID + " blev ikke fundet");
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Feltet skal indeholde et heltal");
        }
}//GEN-LAST:event_btnRemoveSLIActionPerformed

    private void txtAddOrRemoveCustomerIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddOrRemoveCustomerIDFocusGained
        // TODO add your handling code here:
        txtAddOrRemoveCustomerID.setText("");
    }//GEN-LAST:event_txtAddOrRemoveCustomerIDFocusGained

    private void txtItemIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemIDFocusGained
        // TODO add your handling code here:
        txtItemID.setText("");
    }//GEN-LAST:event_txtItemIDFocusGained

    private void txtItemQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemQuantityFocusGained
        // TODO add your handling code here:
        txtItemQuantity.setText("");
    }//GEN-LAST:event_txtItemQuantityFocusGained

    private void txtRemoveSLIIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRemoveSLIIDFocusGained
        // TODO add your handling code here:
        txtRemoveSLIID.setText("");
    }//GEN-LAST:event_txtRemoveSLIIDFocusGained

    private void txtAddQuantityDiscountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddQuantityDiscountFocusGained
        // TODO add your handling code here:
        txtAddQuantityDiscount.setText("");
    }//GEN-LAST:event_txtAddQuantityDiscountFocusGained

    private void txtPickupDiscountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPickupDiscountFocusGained
        // TODO add your handling code here:
        txtPickupDiscount.setText("");
    }//GEN-LAST:event_txtPickupDiscountFocusGained

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        updateSliList();
    }//GEN-LAST:event_formComponentShown

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        saleCtr.cancelSale(saleID);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewSale().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddPickDiscount;
    private javax.swing.JButton btnAddQuantityDiscount;
    private javax.swing.JButton btnAddSLI;
    private javax.swing.JButton btnCancelSale;
    private javax.swing.JButton btnEndSale;
    private javax.swing.JButton btnRemoveCustomer;
    private javax.swing.JButton btnRemoveSLI;
    private javax.swing.JButton btnResetPickupDiscount;
    private javax.swing.JButton btnResetQuantityDiscount;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerAddress;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerPhone;
    private javax.swing.JLabel lblItemID;
    private javax.swing.JLabel lblItemQuantity;
    private javax.swing.JLabel lblPickupDiscount;
    private javax.swing.JLabel lblQuantityDiscount;
    private javax.swing.JLabel lblSLI;
    private javax.swing.JLabel lblTotalDiscount;
    private javax.swing.JPanel pAddDiscount;
    private javax.swing.JPanel pAddItem;
    private javax.swing.JPanel pAddOrRemoveCustomer;
    private javax.swing.JPanel pContentsOfSale;
    private javax.swing.JPanel pCustomer;
    private javax.swing.JPanel pNewSale;
    private javax.swing.JPanel pRemoveItem;
    private javax.swing.JTable tblNewSaleList;
    private javax.swing.JTextField txtAddOrRemoveCustomerID;
    private javax.swing.JTextField txtAddQuantityDiscount;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPhone;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtItemQuantity;
    private javax.swing.JTextField txtPickupDiscount;
    private javax.swing.JTextField txtRemoveSLIID;
    // End of variables declaration//GEN-END:variables
}
