/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchSaleResult.java
 *
 * Created on 14-06-2010, 10:30:59
 */
package GUI;

import Ctr.SaleCtr;
import Model.SalesLineItem;
import java.util.ArrayList;

/**
 *
 * @author Erik
 */
public class SaleContents extends javax.swing.JFrame {

    private int saleID;
    private SaleCtr saleCtr;
    private TableSaleContents tblSaleContents;

    /** Creates new form SearchSaleResult */
    public SaleContents() {
        initComponents();
        saleID = 0;
        saleCtr = new SaleCtr();
        tblSaleContents = new TableSaleContents();
    }

    public void setSaleID(int saleID) {
        this.saleID = saleID;
    }

    public void updateSliList() {
        ArrayList<SalesLineItem> sliList = saleCtr.getSLIList(saleID);
        tblSaleContents.setData(sliList);
        tblSaleContentsList.setModel(tblSaleContents);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pSaleContents = new javax.swing.JPanel();
        lblSaleID = new javax.swing.JLabel();
        lblSaleDate = new javax.swing.JLabel();
        lblSaleTotalPrice = new javax.swing.JLabel();
        lblSaleEmployeeID = new javax.swing.JLabel();
        txtSaleID = new javax.swing.JTextField();
        txtSaleDate = new javax.swing.JTextField();
        txtSaleTotalPrice = new javax.swing.JTextField();
        txtSaleEmployeeID = new javax.swing.JTextField();
        lblSaleCustomerID = new javax.swing.JLabel();
        txtSaleCustomerID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSaleContentsList = new javax.swing.JTable();
        btnSaleContents = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pSaleContents.setBorder(javax.swing.BorderFactory.createTitledBorder("Salgets indhold"));
        pSaleContents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSaleID.setText("Salgs-ID");
        pSaleContents.add(lblSaleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, -1, -1));

        lblSaleDate.setText("Dato");
        pSaleContents.add(lblSaleDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 65, -1, -1));

        lblSaleTotalPrice.setText("Samlet pris");
        pSaleContents.add(lblSaleTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 107, 112, -1));

        lblSaleEmployeeID.setText("Medarbejder-ID");
        pSaleContents.add(lblSaleEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 153, -1, -1));

        txtSaleID.setEditable(false);
        pSaleContents.add(txtSaleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 40, 112, -1));

        txtSaleDate.setEditable(false);
        pSaleContents.add(txtSaleDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 81, 112, -1));

        txtSaleTotalPrice.setEditable(false);
        pSaleContents.add(txtSaleTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 127, 112, -1));

        txtSaleEmployeeID.setEditable(false);
        pSaleContents.add(txtSaleEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 173, 112, -1));

        lblSaleCustomerID.setText("Kunde-ID");
        pSaleContents.add(lblSaleCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 199, -1, -1));

        txtSaleCustomerID.setEditable(false);
        pSaleContents.add(txtSaleCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 219, 112, -1));

        tblSaleContentsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Vare-ID", "Antal", "Samlet pris"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSaleContentsList);
        tblSaleContentsList.getColumnModel().getColumn(2).setResizable(false);

        pSaleContents.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 371));

        btnSaleContents.setText("OK");
        btnSaleContents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleContentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pSaleContents, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addComponent(btnSaleContents, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSaleContents, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaleContents)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaleContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleContentsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnSaleContentsActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        String toStringSaleID = Integer.toString(saleID);
        String toStringDate = saleCtr.getSale(saleID).getDate();
        String toStringPrice = Double.toString(saleCtr.getSale(saleID).getPrice());
        String toStringEmployeeID = Integer.toString(saleCtr.getSale(saleID).getEmployee().getEmployeeID());
        String toStringCustomerID = Integer.toString(saleCtr.getSale(saleID).getCustomer().getCustomerID());
        txtSaleID.setText(toStringSaleID);
        txtSaleDate.setText(toStringDate);
        txtSaleEmployeeID.setText(toStringEmployeeID);
        txtSaleTotalPrice.setText(toStringPrice);
        txtSaleCustomerID.setText(toStringCustomerID);
        updateSliList();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SaleContents().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaleContents;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSaleCustomerID;
    private javax.swing.JLabel lblSaleDate;
    private javax.swing.JLabel lblSaleEmployeeID;
    private javax.swing.JLabel lblSaleID;
    private javax.swing.JLabel lblSaleTotalPrice;
    private javax.swing.JPanel pSaleContents;
    private javax.swing.JTable tblSaleContentsList;
    private javax.swing.JTextField txtSaleCustomerID;
    private javax.swing.JTextField txtSaleDate;
    private javax.swing.JTextField txtSaleEmployeeID;
    private javax.swing.JTextField txtSaleID;
    private javax.swing.JTextField txtSaleTotalPrice;
    // End of variables declaration//GEN-END:variables
}
