/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Kundehaandtering.java
 *
 * Created on 10-06-2010, 11:07:24
 */
package GUI;

import Ctr.CustomerCtr;
import Model.Customer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Erik
 */
public class Kundehaandtering extends javax.swing.JPanel {

    private CustomerCtr customerCtr;
    private TableCustomer tblCustomer;
    private int customerIDUpdate;

    /** Creates new form Kundehaandtering */
    public Kundehaandtering() {
        initComponents();
        customerCtr = new CustomerCtr();
        tblCustomer = new TableCustomer();
    }

    public void updateCustomerList() {
        ArrayList<Customer> customerList = customerCtr.getCustomerList();
        tblCustomer.setData(customerList);
        tblCustomerList.setModel(tblCustomer);
        this.setVisible(true);
    }

    public void resetFields(JTextField[] textFields) {
        for (JTextField txtField : textFields) {
            txtField.setText("");
        }
    }

    public void enableFields(JTextField[] textFields) {
        for (JTextField txtField : textFields) {
            txtField.setEnabled(true);
        }
    }

    public void disableFields(JTextField[] textFields) {
        for (JTextField txtField : textFields) {
            txtField.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pSearchCustomer = new javax.swing.JPanel();
        btnCustomerSeach = new javax.swing.JButton();
        txtCustomerSearch = new javax.swing.JTextField();
        pCustomerList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerList = new javax.swing.JTable();
        pCreateCustomer = new javax.swing.JPanel();
        lblCustomerName = new java.awt.Label();
        txtCreateCustomerName = new javax.swing.JTextField();
        lblCustomerAddress = new java.awt.Label();
        txtCreateCustomerAddress = new javax.swing.JTextField();
        lblCreateCustomerPhone = new java.awt.Label();
        txtCreateCustomerPhone = new javax.swing.JTextField();
        btnCustomerCreateCustomer = new javax.swing.JButton();
        pDeleteCustomer = new javax.swing.JPanel();
        txtDeleteCustomer = new javax.swing.JTextField();
        btnDeleteCustomer = new javax.swing.JButton();
        pUpdateCustomer = new javax.swing.JPanel();
        lblUpdateCustomerName = new java.awt.Label();
        txtUpdateCustomerName = new javax.swing.JTextField();
        lblUpdateCustomerAddress = new java.awt.Label();
        txtUpdateCustomerAddress = new javax.swing.JTextField();
        lblUpdateCustomerPhone = new java.awt.Label();
        txtUpdateCustomerPhone = new javax.swing.JTextField();
        btnUpdateCustomer = new javax.swing.JButton();
        btnUpdateCustomerGetCustomer = new javax.swing.JButton();
        txtUpdateCustomerGetCustomer = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kundehåndtering"));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        pSearchCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Søg kunde"));

        btnCustomerSeach.setText("Søg");
        btnCustomerSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerSeachActionPerformed(evt);
            }
        });

        txtCustomerSearch.setText("Indtast kunde-ID");
        txtCustomerSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerSearchActionPerformed(evt);
            }
        });
        txtCustomerSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerSearchFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pSearchCustomerLayout = new javax.swing.GroupLayout(pSearchCustomer);
        pSearchCustomer.setLayout(pSearchCustomerLayout);
        pSearchCustomerLayout.setHorizontalGroup(
            pSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchCustomerLayout.createSequentialGroup()
                .addComponent(btnCustomerSeach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCustomerSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        pSearchCustomerLayout.setVerticalGroup(
            pSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnCustomerSeach)
                .addComponent(txtCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pCustomerList.setBorder(javax.swing.BorderFactory.createTitledBorder("Kundeliste"));

        tblCustomerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medarbejder-ID", "Navn", "Adresse", "Tlfnr."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomerList);

        javax.swing.GroupLayout pCustomerListLayout = new javax.swing.GroupLayout(pCustomerList);
        pCustomerList.setLayout(pCustomerListLayout);
        pCustomerListLayout.setHorizontalGroup(
            pCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCustomerListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );
        pCustomerListLayout.setVerticalGroup(
            pCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomerListLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pCreateCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Opret kunde"));

        lblCustomerName.setText("Navn");

        lblCustomerAddress.setText("Adresse");

        lblCreateCustomerPhone.setText("Tlfnr.");

        btnCustomerCreateCustomer.setText("Opret");
        btnCustomerCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerCreateCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCreateCustomerLayout = new javax.swing.GroupLayout(pCreateCustomer);
        pCreateCustomer.setLayout(pCreateCustomerLayout);
        pCreateCustomerLayout.setHorizontalGroup(
            pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCreateCustomerLayout.createSequentialGroup()
                        .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCreateCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCreateCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtCreateCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtCreateCustomerPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                    .addComponent(btnCustomerCreateCustomer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pCreateCustomerLayout.setVerticalGroup(
            pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateCustomerLayout.createSequentialGroup()
                .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCreateCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCustomerCreateCustomer)
                .addContainerGap())
        );

        pDeleteCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Slet kunde"));

        btnDeleteCustomer.setText("Slet");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDeleteCustomerLayout = new javax.swing.GroupLayout(pDeleteCustomer);
        pDeleteCustomer.setLayout(pDeleteCustomerLayout);
        pDeleteCustomerLayout.setHorizontalGroup(
            pDeleteCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDeleteCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeleteCustomer)
                .addGap(18, 18, 18)
                .addComponent(txtDeleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        pDeleteCustomerLayout.setVerticalGroup(
            pDeleteCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDeleteCustomerLayout.createSequentialGroup()
                .addGroup(pDeleteCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCustomer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pUpdateCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Opdater kunde"));

        lblUpdateCustomerName.setText("Navn");

        txtUpdateCustomerName.setEnabled(false);

        lblUpdateCustomerAddress.setText("Adresse");

        txtUpdateCustomerAddress.setEnabled(false);

        lblUpdateCustomerPhone.setText("Tlfnr.");

        txtUpdateCustomerPhone.setEnabled(false);

        btnUpdateCustomer.setText("Opret");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        btnUpdateCustomerGetCustomer.setText("Hent");
        btnUpdateCustomerGetCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerGetCustomerActionPerformed(evt);
            }
        });

        txtUpdateCustomerGetCustomer.setText("Indtast kunde-ID");
        txtUpdateCustomerGetCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCustomerGetCustomerActionPerformed(evt);
            }
        });
        txtUpdateCustomerGetCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUpdateCustomerGetCustomerFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pUpdateCustomerLayout = new javax.swing.GroupLayout(pUpdateCustomer);
        pUpdateCustomer.setLayout(pUpdateCustomerLayout);
        pUpdateCustomerLayout.setHorizontalGroup(
            pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pUpdateCustomerLayout.createSequentialGroup()
                        .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateCustomerGetCustomer)
                            .addComponent(lblUpdateCustomerPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(lblUpdateCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUpdateCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUpdateCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtUpdateCustomerPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtUpdateCustomerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtUpdateCustomerGetCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pUpdateCustomerLayout.setVerticalGroup(
            pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateCustomerLayout.createSequentialGroup()
                .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCustomerGetCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCustomerGetCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUpdateCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpdateCustomerAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateCustomerAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUpdateCustomerPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateCustomerPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdateCustomer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pSearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pCustomerList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pCreateCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDeleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pUpdateCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pCustomerList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerSeachActionPerformed
        // TODO add your handling code here:
        try {
            int customerID = Integer.parseInt(txtCustomerSearch.getText());
            if (customerCtr.getCustomer(customerID) != null) {
                customerCtr.getCustomer(customerID);
                txtCustomerSearch.setText("");
                int rows = tblCustomerList.getModel().getRowCount();
                int col = 0;
                for (int i = 0; i < rows; i++) {
                    int value = (Integer) tblCustomerList.getModel().getValueAt(i, col);
                    if (value == customerID) {
                        tblCustomerList.setRowSelectionInterval(i, i);
                        tblCustomerList.addRowSelectionInterval(i, i);
                        tblCustomerList.scrollRectToVisible(tblCustomerList.getCellRect(i, i, true));
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "ID'et " + customerID + " blev ikke fundet");
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Skal være et heltal");
            txtCustomerSearch.setText("");
        }
}//GEN-LAST:event_btnCustomerSeachActionPerformed

    private void txtCustomerSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerSearchActionPerformed
        // TODO add your handling code here:
        txtCustomerSearch.setText("");
}//GEN-LAST:event_txtCustomerSearchActionPerformed

    private void txtCustomerSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerSearchFocusGained
        // TODO add your handling code here:
        txtCustomerSearch.setText("");
}//GEN-LAST:event_txtCustomerSearchFocusGained

    private void btnCustomerCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerCreateCustomerActionPerformed
        // TODO add your handling code here:
        try {
            String customerName = txtCreateCustomerName.getText();
            String customerAddress = txtCreateCustomerAddress.getText();
            String customerPhone = txtCreateCustomerPhone.getText();
            JTextField[] txtFields = {txtCreateCustomerName,
                txtCreateCustomerAddress, txtCreateCustomerPhone};
            if (customerName.trim().isEmpty() || customerAddress.trim().isEmpty() || customerPhone.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Udfyld venligst alle felterne");
            } else {
                int customerID = customerCtr.createCustomer(customerName, customerAddress, customerPhone);
                updateCustomerList();
                resetFields(txtFields);
                JOptionPane.showMessageDialog(this, "En medarbejder med ID'et " + customerID);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fejl: " + e.getMessage());
        }
}//GEN-LAST:event_btnCustomerCreateCustomerActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        // TODO add your handling code here:
        int customerID = 0;
        try {
            customerID = Integer.parseInt(txtDeleteCustomer.getText());
            if (customerCtr.getCustomer(customerID) != null) {
                customerCtr.deleteCustomer(customerID);
                updateCustomerList();
                txtDeleteCustomer.setText("");
                //Efterfølgende er for at nulstille opdater vare vinduet.
                //Dette forhindrer brugeren at opdaterer en vare,
                //som ikke eksisterer.
                JTextField[] txtFields = {txtUpdateCustomerName, txtUpdateCustomerAddress,
                    txtUpdateCustomerPhone};
                resetFields(txtFields);
                disableFields(txtFields);
                txtUpdateCustomerGetCustomer.setText("");
                JOptionPane.showMessageDialog(this, "Varen med ID'et " + customerID + " blev slettet");

            } else {

                JOptionPane.showMessageDialog(this, "ID'et " + customerID + " blev ikke fundet");
                txtDeleteCustomer.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Skal være et heltal");
            txtDeleteCustomer.setText("");
        }
}//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:
        try {
            //            int customerID = Integer.parseInt(txtUpdateCustomergetCustomer.getText());
            //            if (customerID == 0) {
            //                throw new IllegalStateException();
            //            }
            String customerName = txtUpdateCustomerName.getText();
            String customerAddress = txtUpdateCustomerAddress.getText();
            String customerPhone = txtUpdateCustomerPhone.getText();
            customerCtr.updateName(customerIDUpdate, customerName);
            customerCtr.updateAddress(customerIDUpdate, customerAddress);
            customerCtr.updatePhone(customerIDUpdate, customerPhone);
            JTextField[] txtFields = {txtUpdateCustomerName, txtUpdateCustomerAddress,
                txtUpdateCustomerPhone};
            updateCustomerList();
            resetFields(txtFields);
            disableFields(txtFields);
            txtUpdateCustomerGetCustomer.setText("");
            JOptionPane.showMessageDialog(this, "Medarbejderen med ID'et " + customerIDUpdate + " er blevet opdateret");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fejl: " + e.getMessage());
        }
}//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnUpdateCustomerGetCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerGetCustomerActionPerformed
        // TODO add your handling code here:
        try {
            int customerID = Integer.parseInt(txtUpdateCustomerGetCustomer.getText());
            if (customerCtr.getCustomer(customerID) != null) {
                customerIDUpdate = customerID;
                JTextField[] txtFields = {txtUpdateCustomerName, txtUpdateCustomerAddress,
                    txtUpdateCustomerPhone};
                enableFields(txtFields);
                txtUpdateCustomerName.setText(customerCtr.getCustomer(customerID).getName());
                txtUpdateCustomerAddress.setText(customerCtr.getCustomer(customerID).getAddress());
                txtUpdateCustomerPhone.setText(customerCtr.getCustomer(customerID).getPhone());
            } else {
                JOptionPane.showMessageDialog(this, "ID'et blev ikke fundet");
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Skal være et heltal");
        }
}//GEN-LAST:event_btnUpdateCustomerGetCustomerActionPerformed

    private void txtUpdateCustomerGetCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCustomerGetCustomerActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtUpdateCustomerGetCustomerActionPerformed

    private void txtUpdateCustomerGetCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUpdateCustomerGetCustomerFocusGained
        // TODO add your handling code here:
        txtUpdateCustomerGetCustomer.setText("");
}//GEN-LAST:event_txtUpdateCustomerGetCustomerFocusGained

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
}//GEN-LAST:event_jPanel1ComponentShown
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerCreateCustomer;
    private javax.swing.JButton btnCustomerSeach;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JButton btnUpdateCustomerGetCustomer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lblCreateCustomerPhone;
    private java.awt.Label lblCustomerAddress;
    private java.awt.Label lblCustomerName;
    private java.awt.Label lblUpdateCustomerAddress;
    private java.awt.Label lblUpdateCustomerName;
    private java.awt.Label lblUpdateCustomerPhone;
    private javax.swing.JPanel pCreateCustomer;
    private javax.swing.JPanel pCustomerList;
    private javax.swing.JPanel pDeleteCustomer;
    private javax.swing.JPanel pSearchCustomer;
    private javax.swing.JPanel pUpdateCustomer;
    private javax.swing.JTable tblCustomerList;
    private javax.swing.JTextField txtCreateCustomerAddress;
    private javax.swing.JTextField txtCreateCustomerName;
    private javax.swing.JTextField txtCreateCustomerPhone;
    private javax.swing.JTextField txtCustomerSearch;
    private javax.swing.JTextField txtDeleteCustomer;
    private javax.swing.JTextField txtUpdateCustomerAddress;
    private javax.swing.JTextField txtUpdateCustomerGetCustomer;
    private javax.swing.JTextField txtUpdateCustomerName;
    private javax.swing.JTextField txtUpdateCustomerPhone;
    // End of variables declaration//GEN-END:variables
}
