/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Kundehaandtering.java
 *
 * Created on 10-06-2010, 11:07:24
 */
package GUI;

import Ctr.CustomerCtr;
import Ctr.RentCtr;
import Model.Customer;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Erik
 */
public class Kundehaandtering extends javax.swing.JPanel {

    private CustomerCtr customerCtr;
    private RentCtr rentCtr;
    private TableCustomer tblCustomer;
    private int customerIDUpdate;

    /** Creates new form Kundehaandtering */
    public Kundehaandtering() {
        initComponents();
        customerCtr = new CustomerCtr();
        rentCtr = new RentCtr();
        tblCustomer = new TableCustomer();
    }

    public void updateCustomerList() {
        ArrayList<Customer> customerList = customerCtr.getCustomerList();
        tblCustomer.setData(customerList);
        tblCustomerList.setModel(tblCustomer);
        tblCustomerList.setAutoCreateRowSorter(true);
//        this.setVisible(true);
//        tblCustomerList.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
//        tblCustomerList.getColumnModel().getColumn(0).setPreferredWidth(2);

    }

    public void resetFields(JTextField[] textFields) {
        for (JTextField txtField : textFields) {
            txtField.setText("");
        }
    }

    public void enableFields(JTextField[] textFields) {
        for (JTextField txtField : textFields) {
            txtField.setEnabled(true);
        }
    }

    public void disableFields(JTextField[] textFields) {
        for (JTextField txtField : textFields) {
            txtField.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCustomerList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerList = new javax.swing.JTable();
        btnCustomerSeach = new javax.swing.JButton();
        txtCustomerSearch = new javax.swing.JTextField();
        pCreateCustomer = new javax.swing.JPanel();
        txtCreateCustomerName = new javax.swing.JTextField();
        txtCreateCustomerAddress = new javax.swing.JTextField();
        txtCreateCustomerPhone = new javax.swing.JTextField();
        btnCustomerCreateCustomer = new javax.swing.JButton();
        lblCustomerName = new javax.swing.JLabel();
        lblCustomerAddress = new javax.swing.JLabel();
        lblCreateCustomerPhone = new javax.swing.JLabel();
        pDeleteCustomer = new javax.swing.JPanel();
        txtDeleteCustomer = new javax.swing.JTextField();
        btnDeleteCustomer = new javax.swing.JButton();
        pUpdateCustomer = new javax.swing.JPanel();
        txtUpdateCustomerName = new javax.swing.JTextField();
        txtUpdateCustomerAddress = new javax.swing.JTextField();
        txtUpdateCustomerPhone = new javax.swing.JTextField();
        btnUpdateCustomer = new javax.swing.JButton();
        btnUpdateCustomerGetCustomer = new javax.swing.JButton();
        txtUpdateCustomerGetCustomer = new javax.swing.JTextField();
        lblUpdateCustomerName = new javax.swing.JLabel();
        lblUpdateCustomerAddress = new javax.swing.JLabel();
        lblUpdateCustomerPhone = new javax.swing.JLabel();

        pCustomerList.setBorder(javax.swing.BorderFactory.createTitledBorder("Kundeliste"));
        pCustomerList.setPreferredSize(new java.awt.Dimension(603, 641));

        tblCustomerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medarbejder-ID", "Navn", "Adresse", "Tlfnr."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomerList);

        btnCustomerSeach.setText("Søg");
        btnCustomerSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerSeachActionPerformed(evt);
            }
        });

        txtCustomerSearch.setText("Indtast kunde-ID");
        txtCustomerSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerSearchActionPerformed(evt);
            }
        });
        txtCustomerSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerSearchFocusGained(evt);
            }
        });
        txtCustomerSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerSearchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerSearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pCustomerListLayout = new javax.swing.GroupLayout(pCustomerList);
        pCustomerList.setLayout(pCustomerListLayout);
        pCustomerListLayout.setHorizontalGroup(
            pCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomerListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addGroup(pCustomerListLayout.createSequentialGroup()
                        .addComponent(btnCustomerSeach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pCustomerListLayout.setVerticalGroup(
            pCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomerListLayout.createSequentialGroup()
                .addGroup(pCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomerSeach)
                    .addComponent(txtCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );

        pCreateCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Opret kunde"));

        btnCustomerCreateCustomer.setText("Opret");
        btnCustomerCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerCreateCustomerActionPerformed(evt);
            }
        });

        lblCustomerName.setText("Navn:");

        lblCustomerAddress.setText("Adresse:");

        lblCreateCustomerPhone.setText("Tlfnr.:");

        javax.swing.GroupLayout pCreateCustomerLayout = new javax.swing.GroupLayout(pCreateCustomer);
        pCreateCustomer.setLayout(pCreateCustomerLayout);
        pCreateCustomerLayout.setHorizontalGroup(
            pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCreateCustomerLayout.createSequentialGroup()
                        .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCreateCustomerPhone)
                            .addComponent(lblCustomerAddress)
                            .addComponent(lblCustomerName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCreateCustomerAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(txtCreateCustomerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(txtCreateCustomerPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)))
                    .addComponent(btnCustomerCreateCustomer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pCreateCustomerLayout.setVerticalGroup(
            pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateCustomerLayout.createSequentialGroup()
                .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreateCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreateCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreateCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateCustomerPhone))
                .addGap(18, 18, 18)
                .addComponent(btnCustomerCreateCustomer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pDeleteCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Slet kunde"));

        btnDeleteCustomer.setText("Slet");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDeleteCustomerLayout = new javax.swing.GroupLayout(pDeleteCustomer);
        pDeleteCustomer.setLayout(pDeleteCustomerLayout);
        pDeleteCustomerLayout.setHorizontalGroup(
            pDeleteCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDeleteCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDeleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );
        pDeleteCustomerLayout.setVerticalGroup(
            pDeleteCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDeleteCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnDeleteCustomer))
        );

        pUpdateCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Opdater kunde"));

        txtUpdateCustomerName.setEnabled(false);

        txtUpdateCustomerAddress.setEnabled(false);

        txtUpdateCustomerPhone.setEnabled(false);

        btnUpdateCustomer.setText("Opret");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        btnUpdateCustomerGetCustomer.setText("Hent");
        btnUpdateCustomerGetCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerGetCustomerActionPerformed(evt);
            }
        });

        txtUpdateCustomerGetCustomer.setText("Indtast kunde-ID");
        txtUpdateCustomerGetCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCustomerGetCustomerActionPerformed(evt);
            }
        });
        txtUpdateCustomerGetCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUpdateCustomerGetCustomerFocusGained(evt);
            }
        });

        lblUpdateCustomerName.setText("Navn:");

        lblUpdateCustomerAddress.setText("Adresse:");

        lblUpdateCustomerPhone.setText("Tlfnr.:");

        javax.swing.GroupLayout pUpdateCustomerLayout = new javax.swing.GroupLayout(pUpdateCustomer);
        pUpdateCustomer.setLayout(pUpdateCustomerLayout);
        pUpdateCustomerLayout.setHorizontalGroup(
            pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pUpdateCustomerLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUpdateCustomerAddress)
                            .addComponent(lblUpdateCustomerName)
                            .addComponent(lblUpdateCustomerPhone)
                            .addComponent(btnUpdateCustomerGetCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUpdateCustomerPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(txtUpdateCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(txtUpdateCustomerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(txtUpdateCustomerGetCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pUpdateCustomerLayout.setVerticalGroup(
            pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateCustomerLayout.createSequentialGroup()
                .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCustomerGetCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCustomerGetCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateCustomerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateCustomerAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateCustomerPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdateCustomer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pCustomerList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pCustomerList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerSeachActionPerformed
        // TODO add your handling code here:
        try {
            int customerID = Integer.parseInt(txtCustomerSearch.getText());
            if (customerCtr.getCustomer(customerID) != null) {
                customerCtr.getCustomer(customerID);
                txtCustomerSearch.setText("");
                int rows = tblCustomerList.getModel().getRowCount();
                int col = 0;
                for (int i = 0; i < rows; i++) {
                    int value = (Integer) tblCustomerList.getModel().getValueAt(i, col);
                    if (value == customerID) {
                        tblCustomerList.setRowSelectionInterval(i, i);
                        tblCustomerList.addRowSelectionInterval(i, i);
                        tblCustomerList.scrollRectToVisible(tblCustomerList.getCellRect(i, i, true));
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "ID'et " + customerID + " blev ikke fundet");
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Skal være et heltal");
            txtCustomerSearch.setText("");
        }
}//GEN-LAST:event_btnCustomerSeachActionPerformed

    private void txtCustomerSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerSearchActionPerformed
        // TODO add your handling code here:
        txtCustomerSearch.setText("");
}//GEN-LAST:event_txtCustomerSearchActionPerformed

    private void txtCustomerSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerSearchFocusGained
        // TODO add your handling code here:
        txtCustomerSearch.setText("");
}//GEN-LAST:event_txtCustomerSearchFocusGained

    private void btnCustomerCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerCreateCustomerActionPerformed
        // TODO add your handling code here:
        try {
            String customerName = txtCreateCustomerName.getText();
            String customerAddress = txtCreateCustomerAddress.getText();
            String customerPhone = txtCreateCustomerPhone.getText();
            JTextField[] txtFields = {txtCreateCustomerName,
                txtCreateCustomerAddress, txtCreateCustomerPhone};
            if (customerName.trim().isEmpty() || customerAddress.trim().isEmpty() || customerPhone.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Udfyld venligst alle felterne");
            } else {
                int customerID = customerCtr.createCustomer(customerName, customerAddress, customerPhone);
                updateCustomerList();
                //resetFields(txtFields);
                JOptionPane.showMessageDialog(this, "En kunde med ID'et " + customerID);
                txtCreateCustomerName.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fejl: " + e.getMessage());
        }
}//GEN-LAST:event_btnCustomerCreateCustomerActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        // TODO add your handling code here:
        int customerID = 0;
//        try {
        customerID = Integer.parseInt(txtDeleteCustomer.getText());
        boolean rentStatus = rentCtr.checkRentStatusCustomer(customerID);
        if (customerCtr.getCustomer(customerID) != null && rentStatus == false) {
            customerCtr.deleteCustomer(customerID);
            updateCustomerList();
            txtDeleteCustomer.setText("");
            //Efterfølgende er for at nulstille opdater vare vinduet.
            //Dette forhindrer brugeren at opdaterer en vare,
            //som ikke eksisterer.
            JTextField[] txtFields = {txtUpdateCustomerName, txtUpdateCustomerAddress,
                txtUpdateCustomerPhone};
            resetFields(txtFields);
            disableFields(txtFields);
            txtUpdateCustomerGetCustomer.setText("");
            JOptionPane.showMessageDialog(this, "Kunden med ID'et " + customerID + " blev slettet");

        } else {
            if (rentStatus == true) {
                JOptionPane.showMessageDialog(this, "Kunden med ID'et " + customerID + " kan ikke slettet, da en udlejning er tilknyttet");

            } else {
                JOptionPane.showMessageDialog(this, "ID'et " + customerID + " blev ikke fundet");
                txtDeleteCustomer.setText("");
            }
        }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Skal være et heltal" + e.getMessage());
//            txtDeleteCustomer.setText("");
//        }
}//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:
        try {
            //            int customerID = Integer.parseInt(txtUpdateCustomergetCustomer.getText());
            //            if (customerID == 0) {
            //                throw new IllegalStateException();
            //            }
            String customerName = txtUpdateCustomerName.getText();
            String customerAddress = txtUpdateCustomerAddress.getText();
            String customerPhone = txtUpdateCustomerPhone.getText();
            customerCtr.updateName(customerIDUpdate, customerName);
            customerCtr.updateAddress(customerIDUpdate, customerAddress);
            customerCtr.updatePhone(customerIDUpdate, customerPhone);
            JTextField[] txtFields = {txtUpdateCustomerName, txtUpdateCustomerAddress,
                txtUpdateCustomerPhone};
            updateCustomerList();
            resetFields(txtFields);
            disableFields(txtFields);
            txtUpdateCustomerGetCustomer.setText("");
            JOptionPane.showMessageDialog(this, "Medarbejderen med ID'et " + customerIDUpdate + " er blevet opdateret");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fejl: " + e.getMessage());
        }
}//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnUpdateCustomerGetCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerGetCustomerActionPerformed
        // TODO add your handling code here:
        try {
            int customerID = Integer.parseInt(txtUpdateCustomerGetCustomer.getText());
            if (customerCtr.getCustomer(customerID) != null) {
                customerIDUpdate = customerID;
                JTextField[] txtFields = {txtUpdateCustomerName, txtUpdateCustomerAddress,
                    txtUpdateCustomerPhone};
                enableFields(txtFields);
                txtUpdateCustomerName.setText(customerCtr.getCustomer(customerID).getName());
                txtUpdateCustomerAddress.setText(customerCtr.getCustomer(customerID).getAddress());
                txtUpdateCustomerPhone.setText(customerCtr.getCustomer(customerID).getPhone());
            } else {
                JOptionPane.showMessageDialog(this, "ID'et blev ikke fundet");
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Skal være et heltal");
        }
}//GEN-LAST:event_btnUpdateCustomerGetCustomerActionPerformed

    private void txtUpdateCustomerGetCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCustomerGetCustomerActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtUpdateCustomerGetCustomerActionPerformed

    private void txtUpdateCustomerGetCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUpdateCustomerGetCustomerFocusGained
        // TODO add your handling code here:
        txtUpdateCustomerGetCustomer.setText("");
}//GEN-LAST:event_txtUpdateCustomerGetCustomerFocusGained

    private void txtCustomerSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerSearchKeyTyped

    private void txtCustomerSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerSearchKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_ENTER) {
            btnCustomerSeach.doClick();
        }
    }//GEN-LAST:event_txtCustomerSearchKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerCreateCustomer;
    private javax.swing.JButton btnCustomerSeach;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JButton btnUpdateCustomerGetCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateCustomerPhone;
    private javax.swing.JLabel lblCustomerAddress;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblUpdateCustomerAddress;
    private javax.swing.JLabel lblUpdateCustomerName;
    private javax.swing.JLabel lblUpdateCustomerPhone;
    private javax.swing.JPanel pCreateCustomer;
    private javax.swing.JPanel pCustomerList;
    private javax.swing.JPanel pDeleteCustomer;
    private javax.swing.JPanel pUpdateCustomer;
    private javax.swing.JTable tblCustomerList;
    private javax.swing.JTextField txtCreateCustomerAddress;
    private javax.swing.JTextField txtCreateCustomerName;
    private javax.swing.JTextField txtCreateCustomerPhone;
    private javax.swing.JTextField txtCustomerSearch;
    private javax.swing.JTextField txtDeleteCustomer;
    private javax.swing.JTextField txtUpdateCustomerAddress;
    private javax.swing.JTextField txtUpdateCustomerGetCustomer;
    private javax.swing.JTextField txtUpdateCustomerName;
    private javax.swing.JTextField txtUpdateCustomerPhone;
    // End of variables declaration//GEN-END:variables
}
