/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Lagerstyring.java
 *
 * Created on 09-06-2010, 09:47:16
 */
package GUI;

import Ctr.*;
import Model.Item;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Erik
 */
public class Lagerstyring extends javax.swing.JPanel {

    private TableItem tblItem;
    private ItemCtr itemCtr;
    private int itemIDUpdate;

    /** Creates new form Lagerstyring */
    public Lagerstyring() {
        initComponents();
        itemCtr = new ItemCtr();
        tblItem = new TableItem();
        itemIDUpdate = 0;
    }

    public void updateItemList() {
        ArrayList<Item> itemList = itemCtr.getItemList();
        tblItem.setData(itemList);
        tblItemList.setModel(tblItem);
        this.setVisible(true);

    }

    public void resetFields(JTextField[] textFields) {
        for (JTextField txtField : textFields) {
            txtField.setText("");
        }
    }

    public void enableFields(JTextField[] textFields) {
        for (JTextField txtField : textFields) {
            txtField.setEnabled(true);
        }
    }

    public void disableFields(JTextField[] textFields) {
        for (JTextField txtField : textFields) {
            txtField.setEnabled(false);
        }
    }

    public void isEmpty() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pSearchItem = new javax.swing.JPanel();
        btnItemSeach = new javax.swing.JButton();
        txtItemSearch = new javax.swing.JTextField();
        pItemList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemList = new javax.swing.JTable();
        pCreateItem = new javax.swing.JPanel();
        lblItemName = new java.awt.Label();
        txtCreateItemName = new javax.swing.JTextField();
        lblItemPrice = new java.awt.Label();
        txtCreateItemPrice = new javax.swing.JTextField();
        lblCreateItemDescription = new java.awt.Label();
        txtCreateItemDescription = new javax.swing.JTextField();
        lblCreateItemItemsInStock = new java.awt.Label();
        txtCreateItemItemsInStock = new javax.swing.JTextField();
        lblCreateItemMinInStock = new java.awt.Label();
        txtCreateItemMinInStock = new javax.swing.JTextField();
        lblCreateItemMaxInStock = new java.awt.Label();
        txtCreateItemMaxInStock = new javax.swing.JTextField();
        lblCreateItemBrand = new java.awt.Label();
        txtCreateItemBrand = new javax.swing.JTextField();
        lblCreateItemLocation = new java.awt.Label();
        txtCreateItemLocation = new javax.swing.JTextField();
        btnItemCreateItem = new javax.swing.JButton();
        lblCreateItemLocation1 = new java.awt.Label();
        chkSerialNoYesOrNo = new javax.swing.JCheckBox();
        pDeleteItem = new javax.swing.JPanel();
        txtDeleteItem = new javax.swing.JTextField();
        btnDeleteItem = new javax.swing.JButton();
        pUpdateItem = new javax.swing.JPanel();
        lblUpdateItemName = new java.awt.Label();
        txtUpdateItemName = new javax.swing.JTextField();
        lblUpdateItemPrice = new java.awt.Label();
        txtUpdateItemPrice = new javax.swing.JTextField();
        lblUpdateItemDescription = new java.awt.Label();
        txtUpdateItemDescription = new javax.swing.JTextField();
        lblUpdateItemItemsInStock = new java.awt.Label();
        txtUpdateItemItemsInStock = new javax.swing.JTextField();
        lblUpdateItemMinInStock = new java.awt.Label();
        txtUpdateItemMinInStock = new javax.swing.JTextField();
        lblUpdateItemMaxInStock = new java.awt.Label();
        txtUpdateItemMaxInStock = new javax.swing.JTextField();
        lblUpdateItemBrand = new java.awt.Label();
        txtUpdateItemBrand = new javax.swing.JTextField();
        lblUpdateItemLocation = new java.awt.Label();
        txtUpdateItemLocation = new javax.swing.JTextField();
        btnUpdateItem = new javax.swing.JButton();
        btnUpdateItemGetItem = new javax.swing.JButton();
        txtUpdateItemGetItem = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lagerstyring"));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        pSearchItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Søg vare"));

        btnItemSeach.setText("Søg");
        btnItemSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemSeachActionPerformed(evt);
            }
        });

        txtItemSearch.setText("Indtast vare-ID");
        txtItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemSearchActionPerformed(evt);
            }
        });
        txtItemSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemSearchFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pSearchItemLayout = new javax.swing.GroupLayout(pSearchItem);
        pSearchItem.setLayout(pSearchItemLayout);
        pSearchItemLayout.setHorizontalGroup(
            pSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchItemLayout.createSequentialGroup()
                .addComponent(btnItemSeach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtItemSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );
        pSearchItemLayout.setVerticalGroup(
            pSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnItemSeach)
                .addComponent(txtItemSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pItemList.setBorder(javax.swing.BorderFactory.createTitledBorder("Vareliste"));

        tblItemList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vare-ID", "Navn", "Pris", "Beskrivelse", "Antal", "Min.", "Maks.", "Brand", "Lokation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItemList);

        javax.swing.GroupLayout pItemListLayout = new javax.swing.GroupLayout(pItemList);
        pItemList.setLayout(pItemListLayout);
        pItemListLayout.setHorizontalGroup(
            pItemListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pItemListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );
        pItemListLayout.setVerticalGroup(
            pItemListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pItemListLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pCreateItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Opret vare"));

        lblItemName.setText("Name");

        lblItemPrice.setText("Pris");

        lblCreateItemDescription.setText("Beskrivelse");

        lblCreateItemItemsInStock.setText("Antal");

        lblCreateItemMinInStock.setText("Min.");

        lblCreateItemMaxInStock.setText("Maks.");

        lblCreateItemBrand.setText("Brand");

        lblCreateItemLocation.setText("Lokation");

        btnItemCreateItem.setText("Opret vare");
        btnItemCreateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemCreateItemActionPerformed(evt);
            }
        });

        lblCreateItemLocation1.setText("Serienr.");

        chkSerialNoYesOrNo.setText("(Ja/nej)");
        chkSerialNoYesOrNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSerialNoYesOrNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCreateItemLayout = new javax.swing.GroupLayout(pCreateItem);
        pCreateItem.setLayout(pCreateItemLayout);
        pCreateItemLayout.setHorizontalGroup(
            pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCreateItemLayout.createSequentialGroup()
                        .addComponent(lblCreateItemBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtCreateItemBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addGroup(pCreateItemLayout.createSequentialGroup()
                        .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCreateItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreateItemItemsInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreateItemMinInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreateItemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreateItemLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pCreateItemLayout.createSequentialGroup()
                                .addComponent(chkSerialNoYesOrNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(btnItemCreateItem))
                            .addComponent(txtCreateItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtCreateItemPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtCreateItemItemsInStock, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtCreateItemDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addGroup(pCreateItemLayout.createSequentialGroup()
                                .addComponent(txtCreateItemMinInStock, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCreateItemMaxInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCreateItemMaxInStock, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCreateItemLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pCreateItemLayout.setVerticalGroup(
            pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateItemLayout.createSequentialGroup()
                .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCreateItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCreateItemItemsInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateItemItemsInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCreateItemMinInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateItemMinInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateItemMaxInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateItemMaxInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCreateItemBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateItemBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCreateItemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateItemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateItemLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pCreateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkSerialNoYesOrNo)
                        .addComponent(btnItemCreateItem)))
                .addContainerGap())
        );

        pDeleteItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Slet vare"));

        btnDeleteItem.setText("Slet");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDeleteItemLayout = new javax.swing.GroupLayout(pDeleteItem);
        pDeleteItem.setLayout(pDeleteItemLayout);
        pDeleteItemLayout.setHorizontalGroup(
            pDeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDeleteItemLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnDeleteItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDeleteItem, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        pDeleteItemLayout.setVerticalGroup(
            pDeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDeleteItemLayout.createSequentialGroup()
                .addGroup(pDeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteItem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pUpdateItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Opdater vare"));

        lblUpdateItemName.setText("Name");

        txtUpdateItemName.setEnabled(false);

        lblUpdateItemPrice.setText("Pris");

        txtUpdateItemPrice.setEnabled(false);

        lblUpdateItemDescription.setText("Beskrivelse");

        txtUpdateItemDescription.setEnabled(false);

        lblUpdateItemItemsInStock.setText("Antal");

        txtUpdateItemItemsInStock.setEnabled(false);

        lblUpdateItemMinInStock.setText("Min.");

        txtUpdateItemMinInStock.setEnabled(false);

        lblUpdateItemMaxInStock.setText("Maks.");

        txtUpdateItemMaxInStock.setEnabled(false);

        lblUpdateItemBrand.setText("Brand");

        txtUpdateItemBrand.setEnabled(false);

        lblUpdateItemLocation.setText("Lokation");

        txtUpdateItemLocation.setEnabled(false);

        btnUpdateItem.setText("Opdate vare");
        btnUpdateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItemActionPerformed(evt);
            }
        });

        btnUpdateItemGetItem.setText("Hent");
        btnUpdateItemGetItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItemGetItemActionPerformed(evt);
            }
        });

        txtUpdateItemGetItem.setText("Indtast vare-ID");
        txtUpdateItemGetItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateItemGetItemActionPerformed(evt);
            }
        });
        txtUpdateItemGetItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUpdateItemGetItemFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pUpdateItemLayout = new javax.swing.GroupLayout(pUpdateItem);
        pUpdateItem.setLayout(pUpdateItemLayout);
        pUpdateItemLayout.setHorizontalGroup(
            pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUpdateItemLayout.createSequentialGroup()
                        .addGroup(pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUpdateItemItemsInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUpdateItemMinInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUpdateItemDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUpdateItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUpdateItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateItemGetItem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUpdateItemGetItem, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtUpdateItemPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtUpdateItemDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtUpdateItemItemsInStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtUpdateItemName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addGroup(pUpdateItemLayout.createSequentialGroup()
                                .addComponent(txtUpdateItemMinInStock, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUpdateItemMaxInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUpdateItemMaxInStock, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUpdateItemLayout.createSequentialGroup()
                        .addComponent(lblUpdateItemBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txtUpdateItemBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addGroup(pUpdateItemLayout.createSequentialGroup()
                        .addComponent(lblUpdateItemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtUpdateItemLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addComponent(btnUpdateItem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pUpdateItemLayout.setVerticalGroup(
            pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateItemLayout.createSequentialGroup()
                .addGroup(pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateItemGetItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateItemGetItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpdateItemName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateItemName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpdateItemPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateItemPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUpdateItemDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateItemDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUpdateItemItemsInStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateItemItemsInStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUpdateItemMinInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateItemMinInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateItemMaxInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateItemMaxInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUpdateItemBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateItemBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pUpdateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpdateItemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateItemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateItem)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pItemList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pUpdateItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pCreateItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDeleteItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pItemList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pCreateItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pUpdateItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnItemCreateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemCreateItemActionPerformed
        // TODO add your handling code here:
        try {
            String itemName = txtCreateItemName.getText();
            double itemPrice = Double.parseDouble(txtCreateItemPrice.getText());
            String description = txtCreateItemDescription.getText();
            int maxInStock = Integer.parseInt(txtCreateItemMaxInStock.getText());
            int minInStock = Integer.parseInt(txtCreateItemMinInStock.getText());
            int itemsInStock = Integer.parseInt(txtCreateItemItemsInStock.getText());
            String brand = txtCreateItemBrand.getText();
            String location = txtCreateItemLocation.getText();
            boolean containsSerialNo = chkSerialNoYesOrNo.isEnabled();
            JTextField[] txtFields = {txtCreateItemName,
                txtCreateItemPrice, txtCreateItemDescription,
                txtCreateItemMaxInStock, txtCreateItemMinInStock,
                txtCreateItemItemsInStock, txtCreateItemBrand,
                txtCreateItemLocation};
            String[] stringArray = {itemName, description, brand, location};
            if (maxInStock <= minInStock) {
                JOptionPane.showMessageDialog(this, "Maksmimumsbeholdningen er mindre end eller lig med minimumsbeholdningen");
            } else {
                if (itemsInStock > maxInStock || itemsInStock < minInStock) {
                    JOptionPane.showMessageDialog(this, "Antallet af eksemplarer skal være indenfor minimums-/maksiumsbeholdningen");
                } else {
                    if (minInStock < 0) {
                        throw new IllegalArgumentException();
                    } else {
                        if (itemName.trim().isEmpty() || description.trim().isEmpty() || brand.trim().isEmpty() || location.trim().isEmpty()) {
                            stringArray.toString().trim().isEmpty();
                            JOptionPane.showMessageDialog(this, "Udfyld venligst alle felterne");
                        } else {
                            itemCtr.createItem(itemName, itemPrice, description, maxInStock, minInStock, itemsInStock, brand, location, containsSerialNo);
                            updateItemList();
                            resetFields(txtFields);
                        }
                    }
                }
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Et tal er påkrævet i felterne maks./min/antal");
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this, "Fejl: Tallet skal mindst være 0");
        }

    }//GEN-LAST:event_btnItemCreateItemActionPerformed

    private void chkSerialNoYesOrNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSerialNoYesOrNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSerialNoYesOrNoActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
        int itemID = 0;
        try {
            itemID = Integer.parseInt(txtDeleteItem.getText());
            if (itemCtr.getItem(itemID) != null) {
                itemCtr.deleteItem(itemID);
                updateItemList();
                txtDeleteItem.setText("");
                //Efterfølgende er for at nulstille opdater vare vinduet.
                //Dette forhindrer brugeren at opdaterer en vare,
                //som ikke eksisterer.
                JTextField[] txtFields = {txtUpdateItemName, txtUpdateItemPrice,
                txtUpdateItemDescription, txtUpdateItemMaxInStock,
                txtUpdateItemMinInStock, txtUpdateItemItemsInStock,
                txtUpdateItemBrand, txtUpdateItemLocation};
                resetFields(txtFields);
                disableFields(txtFields);
                txtUpdateItemGetItem.setText("");
                JOptionPane.showMessageDialog(this, "Varen med ID'et " + itemID + " blev slettet");

            } else {

                JOptionPane.showMessageDialog(this, "ID'et " + itemID + " blev ikke fundet");
                txtDeleteItem.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Skal være et heltal");
            txtDeleteItem.setText("");
        }

    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void btnItemSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemSeachActionPerformed
        // TODO add your handling code here:
        try {
            int itemID = Integer.parseInt(txtItemSearch.getText());
            if (itemCtr.getItem(itemID) != null) {
                itemCtr.getItem(itemID);
                txtItemSearch.setText("");
                int rows = tblItemList.getModel().getRowCount();
                int col = 0;
                for (int i = 0; i < rows; i++) {
                    int value = (Integer) tblItemList.getModel().getValueAt(i, col);
                    if (value == itemID) {
                        tblItemList.setRowSelectionInterval(i, i);
                        tblItemList.addRowSelectionInterval(i, i);
                        tblItemList.scrollRectToVisible(tblItemList.getCellRect(i, i, true));
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "ID'et " + itemID + " blev ikke fundet");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tja, en fejl");
            txtItemSearch.setText("");
        }
    }//GEN-LAST:event_btnItemSeachActionPerformed

    private void txtItemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemSearchActionPerformed
        // TODO add your handling code here:
        txtItemSearch.setText("");
    }//GEN-LAST:event_txtItemSearchActionPerformed

    private void txtUpdateItemGetItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateItemGetItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateItemGetItemActionPerformed

    private void btnUpdateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItemActionPerformed
        // TODO add your handling code here:
        try {
//            int itemID = Integer.parseInt(txtUpdateItemGetItem.getText());
//            if (itemID == 0) {
//                throw new IllegalStateException();
//            }
            String itemName = txtUpdateItemName.getText();
            double itemPrice = Double.parseDouble(txtUpdateItemPrice.getText());
            String description = txtUpdateItemDescription.getText();
            int maxInStock = Integer.parseInt(txtUpdateItemMaxInStock.getText());
            int minInStock = Integer.parseInt(txtUpdateItemMinInStock.getText());
            int itemsInStock = Integer.parseInt(txtUpdateItemItemsInStock.getText());
            String brand = txtUpdateItemBrand.getText();
            String location = txtUpdateItemLocation.getText();
            itemCtr.updateItemName(itemIDUpdate, itemName);
            itemCtr.updateItemPrice(itemIDUpdate, itemPrice);
            itemCtr.updateDescription(itemIDUpdate, description);
            itemCtr.updateMinInStock(itemIDUpdate, minInStock);
            itemCtr.updateMaxInStock(itemIDUpdate, maxInStock);
            itemCtr.updateItemsInStock(itemIDUpdate, itemsInStock, minInStock);
            itemCtr.updateBrand(itemIDUpdate, brand);
            itemCtr.updatePlace(itemIDUpdate, location);
            JTextField[] txtFields = {txtUpdateItemName, txtUpdateItemPrice,
                txtUpdateItemDescription, txtUpdateItemMaxInStock,
                txtUpdateItemMinInStock, txtUpdateItemItemsInStock,
                txtUpdateItemBrand, txtUpdateItemLocation};
            updateItemList();
            resetFields(txtFields);
            disableFields(txtFields);
            txtUpdateItemGetItem.setText("");
            JOptionPane.showMessageDialog(this, "Varen med ID'et " + itemIDUpdate + " er blevet opdateret");
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Et tal er påkrævet i felterne maks./min/antal");
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(this, "ID'et blev ikke fundet");
        } catch (IllegalStateException ise) {
            JOptionPane.showMessageDialog(this, "Indtast ID");
        }
    }//GEN-LAST:event_btnUpdateItemActionPerformed

    private void btnUpdateItemGetItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItemGetItemActionPerformed
        // TODO add your handling code here:
        try {
            int itemID = Integer.parseInt(txtUpdateItemGetItem.getText());
            if (itemCtr.getItem(itemID) != null) {
                itemIDUpdate = itemID;
                JTextField[] txtFields = {txtUpdateItemName, txtUpdateItemPrice,
                    txtUpdateItemDescription, txtUpdateItemMaxInStock,
                    txtUpdateItemMinInStock, txtUpdateItemItemsInStock,
                    txtUpdateItemBrand, txtUpdateItemLocation};
                enableFields(txtFields);
                txtUpdateItemName.setText(itemCtr.getItem(itemID).getItemName());
                txtUpdateItemPrice.setText(Double.toString(itemCtr.getItem(itemID).getItemPrice()));
                txtUpdateItemDescription.setText(itemCtr.getItem(itemID).getDescription());
                txtUpdateItemMaxInStock.setText(Integer.toString(itemCtr.getItem(itemID).getMaxInStock()));
                txtUpdateItemMinInStock.setText(Integer.toString(itemCtr.getItem(itemID).getMinInStock()));
                txtUpdateItemItemsInStock.setText(Integer.toString(itemCtr.getItem(itemID).getItemsInStock()));
                txtUpdateItemBrand.setText(itemCtr.getItem(itemID).getBrand());
                txtUpdateItemLocation.setText(itemCtr.getItem(itemID).getPlace());
            } else {
                JOptionPane.showMessageDialog(this, "ID'et blev ikke fundet");
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Skal være et heltal");
        }
    }//GEN-LAST:event_btnUpdateItemGetItemActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentShown

    private void txtItemSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemSearchFocusGained
        // TODO add your handling code here:
        txtItemSearch.setText("");
    }//GEN-LAST:event_txtItemSearchFocusGained

    private void txtUpdateItemGetItemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUpdateItemGetItemFocusGained
        // TODO add your handling code here:
        txtUpdateItemGetItem.setText("");
    }//GEN-LAST:event_txtUpdateItemGetItemFocusGained
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnItemCreateItem;
    private javax.swing.JButton btnItemSeach;
    private javax.swing.JButton btnUpdateItem;
    private javax.swing.JButton btnUpdateItemGetItem;
    private javax.swing.JCheckBox chkSerialNoYesOrNo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lblCreateItemBrand;
    private java.awt.Label lblCreateItemDescription;
    private java.awt.Label lblCreateItemItemsInStock;
    private java.awt.Label lblCreateItemLocation;
    private java.awt.Label lblCreateItemLocation1;
    private java.awt.Label lblCreateItemMaxInStock;
    private java.awt.Label lblCreateItemMinInStock;
    private java.awt.Label lblItemName;
    private java.awt.Label lblItemPrice;
    private java.awt.Label lblUpdateItemBrand;
    private java.awt.Label lblUpdateItemDescription;
    private java.awt.Label lblUpdateItemItemsInStock;
    private java.awt.Label lblUpdateItemLocation;
    private java.awt.Label lblUpdateItemMaxInStock;
    private java.awt.Label lblUpdateItemMinInStock;
    private java.awt.Label lblUpdateItemName;
    private java.awt.Label lblUpdateItemPrice;
    private javax.swing.JPanel pCreateItem;
    private javax.swing.JPanel pDeleteItem;
    private javax.swing.JPanel pItemList;
    private javax.swing.JPanel pSearchItem;
    private javax.swing.JPanel pUpdateItem;
    private javax.swing.JTable tblItemList;
    private javax.swing.JTextField txtCreateItemBrand;
    private javax.swing.JTextField txtCreateItemDescription;
    private javax.swing.JTextField txtCreateItemItemsInStock;
    private javax.swing.JTextField txtCreateItemLocation;
    private javax.swing.JTextField txtCreateItemMaxInStock;
    private javax.swing.JTextField txtCreateItemMinInStock;
    private javax.swing.JTextField txtCreateItemName;
    private javax.swing.JTextField txtCreateItemPrice;
    private javax.swing.JTextField txtDeleteItem;
    private javax.swing.JTextField txtItemSearch;
    private javax.swing.JTextField txtUpdateItemBrand;
    private javax.swing.JTextField txtUpdateItemDescription;
    private javax.swing.JTextField txtUpdateItemGetItem;
    private javax.swing.JTextField txtUpdateItemItemsInStock;
    private javax.swing.JTextField txtUpdateItemLocation;
    private javax.swing.JTextField txtUpdateItemMaxInStock;
    private javax.swing.JTextField txtUpdateItemMinInStock;
    private javax.swing.JTextField txtUpdateItemName;
    private javax.swing.JTextField txtUpdateItemPrice;
    // End of variables declaration//GEN-END:variables
}
