/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMenu.java
 *
 * Created on 09-06-2010, 10:44:05
 */

package GUI;

/**
 *
 * @author Erik
 */
public class MainMenu extends javax.swing.JFrame {

    /** Creates new form MainMenu */
    public MainMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        lagerstyring1 = new GUI.Lagerstyring();
        medarbejderhaandtering1 = new GUI.Medarbejderhaandtering();
        kundehaandtering1 = new GUI.Kundehaandtering();
        gUISale1 = new GUI.GUISale();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("tab1", lagerstyring1);
        jTabbedPane1.addTab("tab2", medarbejderhaandtering1);
        jTabbedPane1.addTab("tab3", kundehaandtering1);
        jTabbedPane1.addTab("tab4", gUISale1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.GUISale gUISale1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private GUI.Kundehaandtering kundehaandtering1;
    private GUI.Lagerstyring lagerstyring1;
    private GUI.Medarbejderhaandtering medarbejderhaandtering1;
    // End of variables declaration//GEN-END:variables

}
