/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FUCKU.java
 *
 * Created on 14-06-2010, 12:13:06
 */

package GUI;

import Ctr.RentCtr;
import Ctr.RentableItemCtr;
import Model.RentableItem;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Erik
 */
public class Udlejning extends javax.swing.JPanel {
        private TableRent tblRent;
    private RentableItemCtr rentableItemCtr;
    private RentCtr rentCtr;
    private GUIRent rent;
    private RentableItem rentableItem;


    /** Creates new form FUCKU */
    public Udlejning() {
        initComponents();
                tblRent = new TableRent();
        rentableItemCtr = new RentableItemCtr();
        rentCtr = new RentCtr();
        rent = new GUIRent();
        rentableItem = new RentableItem();
    }

        public void updateRentItemList() {
        ArrayList<RentableItem> itemList = rentableItemCtr.rentableItemList();
        tblRent.setData(itemList);
        tblRentItemList.setModel(tblRent);
        this.setVisible(true);

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        pRentItemList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRentItemList = new javax.swing.JTable();
        pCreateRentItem = new javax.swing.JPanel();
        lblRentItemName = new java.awt.Label();
        txtCreateRentItemName = new javax.swing.JTextField();
        btnCreateRentItem = new javax.swing.JButton();
        pDeleteRentItem = new javax.swing.JPanel();
        txtDeleteItem = new javax.swing.JTextField();
        btnDeleteRentItem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pRentItem = new javax.swing.JPanel();
        lblRentItemOutName = new java.awt.Label();
        txtCreateRentItemID = new javax.swing.JTextField();
        txtCreateRentDate = new javax.swing.JTextField();
        lblRentItemDate = new java.awt.Label();
        txtCreateRentStatus = new javax.swing.JTextField();
        lblRentItemStatus = new java.awt.Label();
        txtCreateRentCustomerID = new javax.swing.JTextField();
        lblRentItemCustomerID = new java.awt.Label();
        btnCreateRentItem4 = new javax.swing.JButton();
        pDeliverItem = new javax.swing.JPanel();
        lblDeliverRentID = new java.awt.Label();
        txtDeliverRentItem = new javax.swing.JTextField();
        btnDeliverRentItem = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lagerstyring"));
        jPanel2.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        pRentItemList.setBorder(javax.swing.BorderFactory.createTitledBorder("Udlejnings vareliste"));

        tblRentItemList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vare-ID", "Dato", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRentItemList);

        javax.swing.GroupLayout pRentItemListLayout = new javax.swing.GroupLayout(pRentItemList);
        pRentItemList.setLayout(pRentItemListLayout);
        pRentItemListLayout.setHorizontalGroup(
            pRentItemListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRentItemListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );
        pRentItemListLayout.setVerticalGroup(
            pRentItemListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRentItemListLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                .addContainerGap())
        );

        pCreateRentItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Opret udlejnings vare"));

        lblRentItemName.setText("Navn");

        txtCreateRentItemName.setText("Indtast Navn");

        btnCreateRentItem.setText("Opret");
        btnCreateRentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRentItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCreateRentItemLayout = new javax.swing.GroupLayout(pCreateRentItem);
        pCreateRentItem.setLayout(pCreateRentItemLayout);
        pCreateRentItemLayout.setHorizontalGroup(
            pCreateRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateRentItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCreateRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCreateRentItemLayout.createSequentialGroup()
                        .addComponent(lblRentItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(txtCreateRentItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCreateRentItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pCreateRentItemLayout.setVerticalGroup(
            pCreateRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateRentItemLayout.createSequentialGroup()
                .addComponent(txtCreateRentItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateRentItem))
            .addComponent(lblRentItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pDeleteRentItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Slet udlejnings vare"));

        txtDeleteItem.setText("Indtast ID");

        btnDeleteRentItem.setText("Slet");
        btnDeleteRentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRentItemActionPerformed(evt);
            }
        });

        jLabel1.setText("Vare-ID");

        javax.swing.GroupLayout pDeleteRentItemLayout = new javax.swing.GroupLayout(pDeleteRentItem);
        pDeleteRentItem.setLayout(pDeleteRentItemLayout);
        pDeleteRentItemLayout.setHorizontalGroup(
            pDeleteRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDeleteRentItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDeleteRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteRentItem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDeleteRentItemLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(txtDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pDeleteRentItemLayout.setVerticalGroup(
            pDeleteRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDeleteRentItemLayout.createSequentialGroup()
                .addGroup(pDeleteRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRentItem))
        );

        pRentItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Opret lån"));

        lblRentItemOutName.setText("Vare-ID");

        txtCreateRentItemID.setText("Indtast ID");
        txtCreateRentItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateRentItemIDActionPerformed(evt);
            }
        });

        txtCreateRentDate.setText("Indtast Dato");
        txtCreateRentDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateRentDateActionPerformed(evt);
            }
        });

        lblRentItemDate.setText("Dato");

        txtCreateRentStatus.setText("Indtast udlejet/ikke udlejet");
        txtCreateRentStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateRentStatusActionPerformed(evt);
            }
        });

        lblRentItemStatus.setText("Status");

        txtCreateRentCustomerID.setText("Indtast ID");
        txtCreateRentCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateRentCustomerIDActionPerformed(evt);
            }
        });

        lblRentItemCustomerID.setText("Kunde-ID");

        btnCreateRentItem4.setText("Opret");
        btnCreateRentItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRentItem4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pRentItemLayout = new javax.swing.GroupLayout(pRentItem);
        pRentItem.setLayout(pRentItemLayout);
        pRentItemLayout.setHorizontalGroup(
            pRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRentItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCreateRentItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pRentItemLayout.createSequentialGroup()
                        .addGroup(pRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRentItemOutName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRentItemDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRentItemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRentItemCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(pRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCreateRentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreateRentItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreateRentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreateRentCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pRentItemLayout.setVerticalGroup(
            pRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRentItemLayout.createSequentialGroup()
                .addGroup(pRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCreateRentItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRentItemOutName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCreateRentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRentItemDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCreateRentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRentItemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRentItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRentItemLayout.createSequentialGroup()
                        .addComponent(txtCreateRentCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateRentItem4))
                    .addComponent(lblRentItemCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pDeliverItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Aflevering"));

        lblDeliverRentID.setText("Vare-ID");

        txtDeliverRentItem.setText("Indtast ID");

        btnDeliverRentItem.setText("Aflever");
        btnDeliverRentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliverRentItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDeliverItemLayout = new javax.swing.GroupLayout(pDeliverItem);
        pDeliverItem.setLayout(pDeliverItemLayout);
        pDeliverItemLayout.setHorizontalGroup(
            pDeliverItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDeliverItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDeliverItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDeliverItemLayout.createSequentialGroup()
                        .addComponent(lblDeliverRentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(txtDeliverRentItem, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDeliverRentItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pDeliverItemLayout.setVerticalGroup(
            pDeliverItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDeliverItemLayout.createSequentialGroup()
                .addComponent(txtDeliverRentItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeliverRentItem))
            .addComponent(lblDeliverRentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pRentItemList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pDeleteRentItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pRentItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDeliverItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pCreateRentItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pRentItemList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pCreateRentItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pDeleteRentItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pRentItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pDeliverItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateRentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRentItemActionPerformed
        // TODO add your handling code here:
        try{
            String rentItemName = txtCreateRentItemName.getText();
            rentableItemCtr.createItem(rentItemName);
            updateRentItemList();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Fejl 40");
        }
}//GEN-LAST:event_btnCreateRentItemActionPerformed

    private void btnDeleteRentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRentItemActionPerformed
        // TODO add your handling code here:
        try{
            int rentItemID = Integer.parseInt(txtDeleteItem.getText());
            rentableItemCtr.deleteRentableItem(rentItemID);
            updateRentItemList();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Udlejnings vare-ID findes ikke");
        }
}//GEN-LAST:event_btnDeleteRentItemActionPerformed

    private void txtCreateRentItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateRentItemIDActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtCreateRentItemIDActionPerformed

    private void txtCreateRentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateRentDateActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtCreateRentDateActionPerformed

    private void txtCreateRentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateRentStatusActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtCreateRentStatusActionPerformed

    private void txtCreateRentCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateRentCustomerIDActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtCreateRentCustomerIDActionPerformed

    private void btnCreateRentItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRentItem4ActionPerformed
        // TODO add your handling code here:
        try{
            int itemID = Integer.parseInt(txtCreateRentItemID.getText());
            String dato = txtCreateRentDate.getText();
            String status = txtCreateRentStatus.getText();
            int customerID = Integer.parseInt(txtCreateRentCustomerID.getText());
            rentCtr.rentItem(itemID, dato, status, customerID);
            updateRentItemList();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "En af de anførte parametre er ikke korrekt");
        }
}//GEN-LAST:event_btnCreateRentItem4ActionPerformed

    private void btnDeliverRentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliverRentItemActionPerformed
        // TODO add your handling code here:
        try{
            int rentItemID = Integer.parseInt(txtDeliverRentItem.getText());
            rentCtr.deliverItem(rentItemID);
            updateRentItemList();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Udlejnings vare-ID findes ikke");
        }
}//GEN-LAST:event_btnDeliverRentItemActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
}//GEN-LAST:event_jPanel2ComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateRentItem;
    private javax.swing.JButton btnCreateRentItem4;
    private javax.swing.JButton btnDeleteRentItem;
    private javax.swing.JButton btnDeliverRentItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lblDeliverRentID;
    private java.awt.Label lblRentItemCustomerID;
    private java.awt.Label lblRentItemDate;
    private java.awt.Label lblRentItemName;
    private java.awt.Label lblRentItemOutName;
    private java.awt.Label lblRentItemStatus;
    private javax.swing.JPanel pCreateRentItem;
    private javax.swing.JPanel pDeleteRentItem;
    private javax.swing.JPanel pDeliverItem;
    private javax.swing.JPanel pRentItem;
    private javax.swing.JPanel pRentItemList;
    private javax.swing.JTable tblRentItemList;
    private javax.swing.JTextField txtCreateRentCustomerID;
    private javax.swing.JTextField txtCreateRentDate;
    private javax.swing.JTextField txtCreateRentItemID;
    private javax.swing.JTextField txtCreateRentItemName;
    private javax.swing.JTextField txtCreateRentStatus;
    private javax.swing.JTextField txtDeleteItem;
    private javax.swing.JTextField txtDeliverRentItem;
    // End of variables declaration//GEN-END:variables

}
